# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: 'Build and deploy ASP.Net Core app to Azure Web App - app-pscidemo'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  AZURE_WEB_APP_NAME: 'app-pcsidemo'
  AZURE_WEBAPP_PACKAGE_PATH: '.'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release

    - name: Publish
      run: dotnet publish -c Release --property:PublishDir='${{env.DOTNET_ROOT}}/myapp'
    
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp
          
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
          name: .net-app
    
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v3
      with:
          app-name: ${{ env.AZURE_WEB_APP_NAME }}
          slot-name: 'development'
          publish-profile: ${{ secrets.AZURE_WEB_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
